import React, { useState } from 'react';
import { UploadCloud } from 'lucide-react';

export default function CsvUpload({ onDataLoaded }) {
  const [file, setFile] = useState(null);
  const [error, setError] = useState(null);

  const handleFileChange = (e) => {
    const selected = e.target.files[0];
    if (selected && selected.name.endsWith('.csv')) {
      setFile(selected);
      setError(null);
    } else {
      setFile(null);
      setError('Please select a valid CSV file.');
    }
  };

  const handleUpload = async () => {
    if (!file) return;
    
    try {
      const formData = new FormData();
      formData.append('file', file);
      
      const API_BASE = import.meta.env.VITE_API_BASE_URL || '';
      const axios = (await import('axios')).default;
      
      const res = await axios.post(`${API_BASE}/api/upload-csv`, formData, {
        headers: { 'Content-Type': 'multipart/form-data' }
      });
      
      onDataLoaded(res.data);
    } catch (err) {
      console.error(err);
      setError("Failed to upload and parse CSV. Ensure it is a valid Gitlytics history file.");
    }
  };

  return (
    <div className="fade-in">
      <div style={{ marginBottom: '24px' }}>
        <h3 style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '8px' }}>
          <UploadCloud size={20} color="var(--accent-color)" /> Analyze Historical CSV
        </h3>
        <p className="text-secondary" style={{ fontSize: '14px', lineHeight: '1.5' }}>
          Upload a CSV generated by the Gitlytics GitHub Action to analyze your historical traffic beyond the 14-day limit.
        </p>
      </div>

      <div 
        style={{
          border: '1px dashed var(--border-color)',
          borderRadius: '8px',
          padding: '40px 20px',
          textAlign: 'center',
          backgroundColor: 'var(--bg-hover)',
          marginBottom: '24px',
          position: 'relative'
        }}
      >
        <input 
          type="file" 
          accept=".csv" 
          onChange={handleFileChange} 
          style={{
            position: 'absolute', top: 0, left: 0, width: '100%', height: '100%', opacity: 0, cursor: 'pointer'
          }}
        />
        {file ? (
          <div style={{ color: 'var(--text-primary)', fontWeight: 500 }}>
            <span style={{ color: 'var(--accent-color)' }}>{file.name}</span> selected
          </div>
        ) : (
          <div style={{ color: 'var(--text-secondary)', fontSize: '14px' }}>
            Drag and drop your CSV here, or click to browse
          </div>
        )}
      </div>

      {error && <div style={{ color: 'var(--danger-color)', fontSize: '14px', marginBottom: '16px' }}>{error}</div>}

      <div style={{ display: 'flex', justifyContent: 'space-between' }}>
        <button 
          className="btn" 
          style={{ backgroundColor: 'transparent', border: '1px solid var(--border-color)', color: 'var(--text-primary)' }}
          onClick={() => setFile(null)}
          disabled={!file}
        >
          Clear
        </button>
        <button 
          className="btn btn-primary" 
          onClick={handleUpload} 
          disabled={!file}
          style={{ backgroundColor: 'white', color: 'black', fontWeight: 600 }}
        >
          Upload & Analyze
        </button>
      </div>
    </div>
  );
}
